export const TOUCH_OPACITY = 0.7

// Screens names
export const HOME_SCREEN = "Home"
export const SIGNIN_SCREEN = "SignIn"
export const FORGOT_PASSWORD_SCREEN = "ForgotPassword"
export const SIGNUP_SCREEN = "SignUp"
export const TRANSACTIONS_SCREEN = "Transactions"
export const LIMITS_SCREEN = "Limits"
export const LIMIT_EDIT_SCREEN = "LimitEdit"
export const LIMIT_DETAILS_SCREEN = "LimitDetails"
export const SETTINGS_SCREEN = "Settings"
export const EMAIL_CHANGE_SCREEN = "EmailChange"
export const PASSWORD_CHANGE_SCREEN = "PasswordChange"
export const PROFILE_SCREEN = "Profile"
export const DELETE_ACCOUNT_SCREEN = "DeleteAccount"
export const REPORT_DAILY_SCREEN = "ReportDaily"
export const REPORT_MONTH_SCREEN = "ReportMonth"
export const BUDGET_SCREEN = "Budget"
export const MONOBANK_SCREEN = "Monobank"
